---
# tasks file for mami.sshd.security

- name: Replace sshd_config from template
  template: src='{{ sshFileDir }}{{ sshFilesshd }}' dest=/etc/ssh/sshd_config owner=root group=root mode=0600 backup=yes
  notify: "restart sshd"
